### ISSUE TITLE
Why close issue without any response?

### ISSUE THREAD

**Issue by jinfagang** [rwightman/efficientdet-pytorch#101]
Why close issue without any response?

**Comment by rwightman** [comment]
Because they are not helpful. You don't file enough info to debug or verify anything, they are often duplicates or based on mistakes on your part.

**Comment by Lincoln93** [comment]
@rwightman Please notify before closing. Otherwise, It's really irritating to find where my issue get placed! -_-

**Comment by jinfagang** [comment]
@rwightman I tried using coco format to train cityscapes, the mAP got 19 than not increase anymore, I am using D0 only. so wired. Also I have tried any implmentation, almost same result.
