### ISSUE TITLE
TypeError: expected Tensor as element 2 in argument 0, but got numpy.ndarray

### ISSUE THREAD

**Issue by Lincoln93** [rwightman/efficientdet-pytorch#103]
I'm using [Alex kernel ](https://www.kaggle.com/shonenkov/training-efficientdet) which have used your network. However, I'm facing following error message suddenly at the middle of training. 

```
----> 1 run_training()

<ipython-input-20-e1e009ab8f01> in run_training()
     27     fitter = Fitter(model=net, device=device, config=TrainGlobalConfig)
---> 29     fitter.fit(train_loader, val_loader)

<ipython-input-18-5b3d28426703> in fit(self, train_loader, validation_loader)
     33 
     34             t = time.time()
---> 35             summary_loss = self.train_one_epoch(train_loader)
     36 
     37             self.log(f'[RESULT]: Train. Epoch: {self.epoch}, summary_loss: {summary_loss.avg:.5f}, time: {(time.time() - t):.5f}')

<ipython-input-18-5b3d28426703> in train_one_epoch(self, train_loader)
    100             print(images[0].shape)
    101             print(type(images))
--> 102             images = torch.stack(images)
    103             images = images.to(self.device).float()
    104             batch_size = images.shape[0]

TypeError: expected Tensor as element 2 in argument 0, but got numpy.ndarray
```

The issue more is, it mostly shows at the middle of epoch, seems like specific step. I don't understand, if my data loader contains some issue, it must shows such behave for all the image samples. But why it shows at the middle of the training in epoch. Can anyone give me some pointer, what is happening here.

**Comment by rwightman** [comment]
I don't see how that's a bug here. Your stack doesn't show anything related to the model or my training code. Figure out where the numpy array is coming from. Everything being passed to the model needs to be torch tensors. My datasets return numpy arrays but the collate fn I use converts them all to torch tesors. Maybe a case is missed when there are no annotations for an image?

**Comment by Lincoln93** [comment]
@rwightman boom, thanks. Solved. In some cases the model did receive some image without annotation. 

One last query, in alex notebook, he used `summary loss`, why not tracking `mAP(0.5:0.95)`? Does it give more sense to track `loss` to pick optimized weights? What should I change in the notebook to receive mAP for each classes? 
Thanks in advance.
