### ISSUE TITLE
Evaluaiton metrics in the training log! 

### ISSUE THREAD

**Issue by Lincoln93** [rwightman/efficientdet-pytorch#104]
@rwightman 
A last query, in [Alex notebook](https://www.kaggle.com/shonenkov/training-efficientdet), he used `summary loss`, why not tracking `mAP(0.5:0.95)`? Does it give more sense to track loss to pick optimized weights? Any pointer, What should I change in the notebook to receive `mAP` for each classes?
Thanks in advance.

**Comment by rwightman** [comment]
@Lincoln93 loss is easy, those mAP scores for coco training are calculated by the coco tools which means you need data in coco format. Upcoming changes add mAP support for other datasets, but not the interpolated multi-point mAP like coco. Just basic mAP@threshold. You'll have to do some digging, I'm not here to tutor people
