### ISSUE TITLE
Missing device argument

### ISSUE THREAD

**Issue by oscarthorn** [rwightman/efficientdet-pytorch#105]
Hi!
Great repo!

There seems to be a missing device argument in effdet/object_detection/argmax_matcher.py on line 109. The tensor created there will be cpu. It's easily fixed by changing the line to:
`return -1 * torch.ones(similarity_matrix.shape[1], dtype=torch.long, device=similarity_matrix.device)`

**Comment by rwightman** [comment]
@oscarthorn it's fixed on a branch I'm planning to merge to master shortly, https://github.com/rwightman/efficientdet-pytorch/tree/more_datasets ... it never cropped up in my COCO training but did on other datasets.

**Comment by oscarthorn** [comment]
Great, thanks!
