### ISSUE TITLE
Background class hard coded

### ISSUE THREAD

**Issue by Ekta246** [rwightman/efficientdet-pytorch#107]
Hi,
I am evaluating my dataset which has 2 classes on efficientdet-d0 based on Pascal metrics
I see while the mode.eval() mode, the test loss is increasing crazy. Also, there is a Warning: WARNING: image 0 does not have groundtruth difficult flag specified.

Is it something to do with not providing the background class while loading the groundtruth annotations into the model?
Also, I cannot make out why the tp_fp_labels always False and 0 which gives 0 mAP.

Any leads appreciated

TIA

**Comment by rwightman** [comment]
0 is always the background class for class targets output from the dataset.

You can ignore that warning, I haven't supported passing difficult flag for Pascal and group_of flag for OpenImages to the evaluator, so detections marked as difficult or group_of won't be treated differently for eval.

As for what's wrong, I don't have any insight. Every dataset is different and there's lots of room to get something not quite right.

**Comment by Ekta246** [comment]
@rwightman,
That's a very good point and insight.
Some writers/authors say while converting the class label(target class
names) to the class_id(integers), to mention the first class as 0 while
some say to mention background as 0.

**Comment by Ekta246** [comment]
@rwightman, since I was getting the mAP 0 every time, and due to the
different author's I was confused with the first class_id hard coded as 0
or not.

Also, I really understand background class is 0.

Thanks

**Comment by rwightman** [comment]
that log is output every x % 1000 == 0 samples when the flags aren't set, has nothing to do with the class labels
