### ISSUE TITLE
Deploy trained weight on video, how?

### ISSUE THREAD

**Issue by Lincoln93** [rwightman/efficientdet-pytorch#110]
To deploy a trained model, do we first need train the model on video data set or we can simply use weight that trained on image data set? Any pointer?

**Comment by rwightman** [comment]
You can just pass images from the video to the model and do it image by image. How close the videos you use are to the original train images are going to be the biggest factor in how well that works. You could also make a custom video model or do post processing of the detections to handle / filte the time dimension and reduce detections 'flickering' between frames. Well beyond the scope of this repository.
