### ISSUE TITLE
Numerous duplicated annotate when predict test-set

### ISSUE THREAD

**Issue by ducviet00** [rwightman/efficientdet-pytorch#115]
I've trained EfficientDet on my custom data. 
My testset has 586 images but when I run validate.py for evaluation, I get a lot of duplicate bbox - 58600 predicted bbox in result.json
thanks

**Comment by rwightman** [comment]
increase the score threshold, filter out the low confidence scores ... the score threshold for eval metrics is really really low. It is not suitable for visualization.

**Comment by ducviet00** [comment]
> increase the score threshold, filter out the low confidence scores ... the score threshold for eval metrics is really really low. It is not suitable for visualization.

Thanks
