### ISSUE TITLE
resizePad bbox scaling incorrectly clipping ymax  (transforms.py)

### ISSUE THREAD

**Issue by lessw2020** [rwightman/efficientdet-pytorch#12]
I am running with the resizepad function in transforms.py and found that the additional clipping code (marked as fixme to be fair) was clipping excessively in terms of rescaling the bboxes:

> if 'bbox' in annotations:

            # FIXME haven't tested this path since not currently using dataset annotations for train/eval
            bbox = annotations['bbox']
            bbox[:, :4] *= scale
            #bbox = clip_boxes(bbox, (scaled_height, scaled_width))
            #indices = np.where(np.sum(bbox, axis=1) != 0)[0]
           # if len(indices) < len(bbox):
                #bbox = np.take(bbox, indices)
               # annotations['cls'] = np.take(annotations['cls'], indices)
            annotations['bbox'] = bbox`

So far I've found that             bbox[:, :4] *= scale
 is sufficient.  The additional code there was introducing incorrect clipping to ymax and I've simply commented out for now.
There might be cases the clipping is needed but I haven't seen it yet and did see that it was incorrectly adjusting the lowest box boundaries (ymax).

**Comment by rwightman** [comment]
I realized I made some late night screwups in my rapidly thrown together flipping and cropping code. Also, seems to be a bug in the reference code for removing empyt bbox. Amazing that it trains as well as it does... 

Not sure why you'd see a y-max issue, unless you are enabling random vflip in which case it would be completely messed up.  Clipping is definitely needed with the scaling + offset augs, it will push parts of boxes or whole boxes off the valid image region.
