### ISSUE TITLE
Metrics: PascalBoxes_Precision/mAP@0.5IOU: 0.0 PascalBoxes_PerformanceByCategory/AP@0.5IOU/drop_inlet: 0.0

### ISSUE THREAD

**Issue by Ekta246** [rwightman/efficientdet-pytorch#122]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
mAP always 0 after validating on every epoch

I am training the model efficientdet-d0 based on pretrained Coco weights from the repo config file on a custom dataset of 1 class only and 1 object per image. I am just resetting the coco head of 90 class to 1 class. Rest of the part trains as it is. There is no freezing of layers
**Describe the solution you'd like**
sense of mAP
**Describe alternatives you've considered**
Do I need to consider freezing of the layers?

**Additional context**

**Comment by rwightman** [comment]
You are using a custom dataset, I cannot help. Please stop creating issues about this.

I did test a one class scenario w/ TFW validator. After only two epochs of training VOC with all but bicyle filtered
```
PascalBoxes_Precision/mAP@0.5IOU: 0.6753591421661145
PascalBoxes_PerformanceByCategory/AP@0.5IOU/bicycle: 0.6753591421661145
```

**Comment by rwightman** [comment]
If you do want help with your custom datasets / applications I charge 225 USD / hr for that sort of work. I canot provide assistance otherwise. I only support fixing bugs in the models here w/ provided open datasets and impl that I have verified myself.

**Comment by Ekta246** [comment]
I hope you have got me wrong. I don't say that it's a bug. I am just
seeking help from the other audience as well if they have reached the same
issue.
Sorry for the misunderstanding.

About the last post, it was labeled as bug by mistake. I am just askinh the
possible reasons to do so.

I am sorry to have wasted your time and your inconvenience.

**Comment by rwightman** [comment]
No worries. I'm really trying to keep the issues down to just bugs and
feature requests right now. It consumes too much time weeding through valid
issues (for me to fix) vs requests for help, etc.

For community help / discussions I'm hoping to activate github Discussions
beta for this repo very soon, it doesn't quite qualify yet.

**Comment by Ekta246** [comment]
Yes, I am really sorry.
