### ISSUE TITLE
[BUG] Wrong function description

### ISSUE THREAD

**Issue by MichaelMonashev** [rwightman/efficientdet-pytorch#123]
**Describe the bug**
Here is https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/anchors.py#L128 described returned values for function generate_detections() as "each row representing [x, y, width, height, score, class]" . But function return [x_min, y_min, x_max, y_max, score, class]

**Comment by rwightman** [comment]
@MichaelMonashev you're welcome to submit a PR for that comment, otherwise I'll get to it with next batch of changes
