### ISSUE TITLE
meanIOU after every epoch for PascalVOC

### ISSUE THREAD

**Issue by Ekta246** [rwightman/efficientdet-pytorch#133]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Since, I am not able to understand why my mAP is 0 in every epoch, I would like to quantify the mean IOU of the class over each epoch. If you could direct me and you think you already do that in the code. 
**Describe the solution you'd like**
np.avg(iou_arrays)
**Describe alternatives you've considered**

**Additional context**

**Comment by rwightman** [comment]
not going to do this
