### ISSUE TITLE
Unable to load a model file once I run training

### ISSUE THREAD

**Issue by haadkhan** [rwightman/efficientdet-pytorch#141]
I used Coco 2017 and looking at the summary.csv it turns out I was able to produce a efficientdet-d0 very close to original results. Now when I try to use create_model script to load the model_best.pth.tar I am unable to load it. I am able to use the create model function to load published weight. 

1. bench = create_model(
        'efficientdet_d0',
        bench_task='predict',
        checkpoint_path='efficientdet_d0-f3276ba8.pth')
Works
2.bench = create_model(
        'efficientdet_d0',
        bench_task='predict',
        checkpoint_path='best_model.pth.tar')

Gives an error
RuntimeError: Error(s) in loading state_dict for EfficientDet:

**Comment by rwightman** [comment]
@haadkhan you didn't include the useful part of the RuntimeError log. I've been prepping some new training weights for release recently so I know this functionality works. Possibility you trained with some hparams that would have impacted the structure of the model? There are some checkpoint compatiblity issues between PyTorch 1.6+ and older PyTorches if you trained in a newer one and go back to old...

**Comment by haadkhan** [comment]
This is the log of the Runtime error I see.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-50-ec9984be2e27> in <module>
      3         bench_task='predict',
      4         num_classes= 90,
----> 5         checkpoint_path=mod)

~/t/efficientdet-pytorch-master/effdet/factory.py in create_model(model_name, bench_task, num_classes, pretrained, checkpoint_path, checkpoint_ema, **kwargs)
     12     return create_model_from_config(
     13         config, bench_task=bench_task, num_classes=num_classes, pretrained=pretrained,
---> 14         checkpoint_path=checkpoint_path, checkpoint_ema=checkpoint_ema, **kwargs)
     15 
     16 

~/t/efficientdet-pytorch-master/effdet/factory.py in create_model_from_config(config, bench_task, num_classes, pretrained, checkpoint_path, checkpoint_ema, **kwargs)
     45     # load an argument specified training checkpoint
     46     if checkpoint_path:
---> 47         load_checkpoint(model, checkpoint_path, use_ema=checkpoint_ema)
     48 
     49     # wrap model in task specific training/prediction bench if set

/opt/conda/lib/python3.6/site-packages/timm-0.2.1-py3.6.egg/timm/models/helpers.py in load_checkpoint(model, checkpoint_path, use_ema, strict)
     46 def load_checkpoint(model, checkpoint_path, use_ema=False, strict=True):
     47     state_dict = load_state_dict(checkpoint_path, use_ema)
---> 48     model.load_state_dict(state_dict, strict=strict)
     49 
     50 

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1043         if len(error_msgs) > 0:
   1044             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1045                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1046         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1047 

RuntimeError: Error(s) in loading state_dict for EfficientDet:

**Comment by haadkhan** [comment]
So I think I am kind of close. 

Here is the issue. 
When I try to do load checkpoint 
m = create_model('efficientdet_d0',checkpoint_path='efficientdet_d0-f3276ba8.pth')
mod = load_checkpoint(m,checkpoint_path = mod)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/opc/mlenv/lib64/python3.6/site-packages/timm/models/helpers.py", line 48, in load_checkpoint
    model.load_state_dict(state_dict, strict=strict)
  File "/home/opc/mlenv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientDet:
        Unexpected key(s) in state_dict: "fpn.resample.3.conv.conv.bias", "fpn.cell.0.fnode.0.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.1.combine.resample.2.conv.conv.bias", "fpn.cell.0.fnode.1.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.2.combine.resample.1.conv.conv.bias", "fpn.cell.0.fnode.2.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.3.combine.resample.0.conv.conv.bias", "fpn.cell.0.fnode.3.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.4.combine.resample.1.conv.conv.bias", "fpn.cell.0.fnode.4.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.5.combine.resample.2.conv.conv.bias", "fpn.cell.0.fnode.5.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.6.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.7.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.0.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.1.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.2.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.3.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.4.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.5.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.6.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.7.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.0.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.1.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.2.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.3.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.4.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.5.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.6.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.7.after_combine.conv.conv_pw.bias", "class_net.conv_rep.0.conv_pw.bias", "class_net.conv_rep.1.conv_pw.bias", "class_net.conv_rep.2.conv_pw.bias", "box_net.conv_rep.0.conv_pw.bias", "box_net.conv_rep.1.conv_pw.bias", "box_net.conv_rep.2.conv_pw.bias". 


Now when I try to load model using redundant_bias=true 
m = create_model('efficientdet_d0'checkpoint_path='efficientdet_d0-f3276ba8.pth',redundant_bias=True)
I get the same error. 

>>> m = create_model(n,checkpoint_path='/home/opc/OD/efficientdet-pytorch-master/efficientdet_d0-f3276ba8.pth',redundant_bias=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/opc/OD/efficientdet-pytorch-master/effdet/factory.py", line 14, in create_model
    checkpoint_path=checkpoint_path, checkpoint_ema=checkpoint_ema, **kwargs)
  File "/home/opc/OD/efficientdet-pytorch-master/effdet/factory.py", line 47, in create_model_from_config
    load_checkpoint(model, checkpoint_path, use_ema=checkpoint_ema)
  File "/home/opc/mlenv/lib64/python3.6/site-packages/timm/models/helpers.py", line 48, in load_checkpoint
    model.load_state_dict(state_dict, strict=strict)
  File "/home/opc/mlenv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientDet:
        Missing key(s) in state_dict: "fpn.resample.3.conv.conv.bias", "fpn.cell.0.fnode.0.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.1.combine.resample.2.conv.conv.bias", "fpn.cell.0.fnode.1.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.2.combine.resample.1.conv.conv.bias", "fpn.cell.0.fnode.2.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.3.combine.resample.0.conv.conv.bias", "fpn.cell.0.fnode.3.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.4.combine.resample.1.conv.conv.bias", "fpn.cell.0.fnode.4.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.5.combine.resample.2.conv.conv.bias", "fpn.cell.0.fnode.5.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.6.after_combine.conv.conv_pw.bias", "fpn.cell.0.fnode.7.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.0.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.1.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.2.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.3.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.4.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.5.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.6.after_combine.conv.conv_pw.bias", "fpn.cell.1.fnode.7.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.0.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.1.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.2.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.3.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.4.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.5.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.6.after_combine.conv.conv_pw.bias", "fpn.cell.2.fnode.7.after_combine.conv.conv_pw.bias", "class_net.conv_rep.0.conv_pw.bias", "class_net.conv_rep.1.conv_pw.bias", "class_net.conv_rep.2.conv_pw.bias", "box_net.conv_rep.0.conv_pw.bias", "box_net.conv_rep.1.conv_pw.bias", "box_net.conv_rep.2.conv_pw.bias". 

I am going to try to load the tf_efficientdet_d0 weights and see how that works.

**Comment by haadkhan** [comment]
So loading tf_efficientdet_d0_(blahblah) as a model before loading checkpoint worked for me.

**Comment by rwightman** [comment]
@haadkhan you either trained an `efficientdet_d0` model w/ redundant bias flag enabled or you trained a `tf_efficientdet_d0` which has redundant bias enabled by default + Tensorflow SAME padding. Either way you need to create the model with the same config you trained with. Use the validation script to verify which one it is (higher mAP score). Also, the `--use-ema` flag tells val script to restore ema copy of weights if you trained with that enabled
