### ISSUE TITLE
Evaluation on unseen test images with no groundtruth annotations

### ISSUE THREAD

**Issue by Ekta246** [rwightman/efficientdet-pytorch#143]
**Is your feature request related to a problem? Please describe.**
Right now, we have to give the groundtruth (annotations) and images(input tensors) and the model checkpoint file in the DetebenchPredict in the validate.py

**Describe the solution you'd like**
What if I have already trained the model on for eg, A class(num_classes 1) and I input the test images but no annotations so as to predict in the real-time environment. I am interested to check the robustness of the model if it detects the other classes as 0 or 1. Ideally, it should not

**Describe alternatives you've considered**
Just run the code for inference and modify the DetBenchPredict.

**Comment by rwightman** [comment]
You can run the model without the predict bench and do whatever you please with it the output and post-process in a fashion suitable for real-time
