### ISSUE TITLE
TypeError: interpolate() got an unexpected keyword argument 'recompute_scale_factor'

### ISSUE THREAD

**Issue by zhilaAI** [rwightman/efficientdet-pytorch#151]
**Describe the bug**

**To Reproduce**
1.
2.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu 18.04]
 - This repository version [e.g. pypi 0.3.1 or branch/commit ref]
 - PyTorch version w/ CUDA/cuDNN  [e.g. from `conda list`, 1.7.0  py3.8_cuda11.0.221_cudnn8.0.3_0]

**Additional context**

**Comment by rwightman** [comment]
info not filled out, you are probably pytorch < 1.6

**Comment by zhilaAI** [comment]
Yes I ma using PyTorch 1.4

**Comment by Ekta246** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1.
> 2.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Windows, Ubuntu 18.04]
> * This repository version [e.g. pypi 0.3.1 or branch/commit ref]
> * PyTorch version w/ CUDA/cuDNN  [e.g. from `conda list`, 1.7.0  py3.8_cuda11.0.221_cudnn8.0.3_0]
> 
> **Additional context**
> Add any other context about the problem here.

Just a work around take out the recompute scale factor argument  on Line 151
