### ISSUE TITLE
[BUG] Height and width is wrong way around in clip_boxes (transforms.py)

### ISSUE THREAD

**Issue by DavidPetrus** [rwightman/efficientdet-pytorch#162]
I think there is a bug when clipping the bounding box annotations. Width and height are switched so Line 57 in transforms.py should be:
clip_upper = np.array([width,height] * 2, dtype=boxes.dtype)

**Comment by rwightman** [comment]
@DavidPetrus The dataset annotations contains bbox in yxyx format by default, do you still believe that to be in error?

**Comment by DavidPetrus** [comment]
Aah I see now, in that case there's now error.
