### ISSUE TITLE
c++ libtorch jit load failed

### ISSUE THREAD

**Issue by dhkdnduq** [rwightman/efficientdet-pytorch#165]
**Describe the bug**

boxes.py

41 line

_assert_has_ops() <-- c++ assert
return torch.ops.torchvision.nms(boxes, scores, iou_threshold)

if use soft_nms ==true 
libtorch load ok. but so slow 

how can  i solve this problem?

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - PyTorch version w/ CUDA/cuDNN  [e.g. from `conda list`, 1.7.0  py3.8_cuda11.0.221_cudnn8.0.3_0]
 - Pytorch &  libtorch v 1.7.1 , py3.8_cuda11.2_cudnn8 
 - 
**Additional context**

solved this problem!
using c++ torchvision 
https://github.com/pytorch/vision/tree/master/torchvision

also hopes that the onnx problem will be solved soon

**Comment by rwightman** [comment]
Not an issue here, I think it's an issue with libtorch/torchvision ops for NMS. Possibly fixed in latest torchvision as per SO link below.

https://stackoverflow.com/questions/65705160/torch-vision-c-interface-error-unknown-builtin-op-torchvisionnms
