### ISSUE TITLE
evaluator not set for validate call in ema branch

### ISSUE THREAD

**Issue by andravin** [rwightman/efficientdet-pytorch#18]
Looks like a recent commit modified the interface to the `validate` function in `train.py` so that it takes an `evaluator` keyword argument. The evaluator is not set in the branch that calls validate for ema. This causes the default 'map' `--eval-metric` to fail.

```bash
Train: 0 [3664/3665 (100%)]  Loss:  3.457180 (3.6070)  Time: 3.425s,    5.25/s  (0.722s,   24.92/s)  LR: 1.000e-04  Data: 0.174 (0.011)
/pytorch/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
Test: [   0/154]  Time: 1.064 (1.064)  Loss:  2.4959 (2.4959)  
Test: [  50/154]  Time: 0.412 (0.428)  Loss:  2.6239 (2.5469)  
Test: [ 100/154]  Time: 0.413 (0.421)  Loss:  2.3167 (2.5493)  
Test: [ 150/154]  Time: 0.410 (0.428)  Loss:  2.5362 (2.5629)  
Test: [ 154/154]  Time: 1.433 (0.434)  Loss:  2.5216 (2.5620)  
Loading and preparing results...
DONE (t=3.12s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=41.79s).
Accumulating evaluation results...
DONE (t=15.55s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.005
Test (EMA): [   0/154]  Time: 1.070 (1.070)  Loss:  2.5276 (2.5276)  
Test (EMA): [  50/154]  Time: 0.378 (0.391)  Loss:  2.6372 (2.5649)  
Test (EMA): [ 100/154]  Time: 0.376 (0.384)  Loss:  2.3414 (2.5664)  
Test (EMA): [ 150/154]  Time: 0.372 (0.382)  Loss:  2.5519 (2.5790)  
Test (EMA): [ 154/154]  Time: 0.376 (0.381)  Loss:  2.5492 (2.5783)  
Traceback (most recent call last):
  File "train.py", line 608, in <module>
    main()
  File "train.py", line 448, in main
    lr_scheduler.step(epoch + 1, eval_metrics[eval_metric])
KeyError: 'map'
```

Here is the code snippet:

https://github.com/rwightman/efficientdet-pytorch/blob/91f517228db2af8be89cf38a35905ec5db104f2c/train.py#L437-L444

Looks like a simple fix .. and workaround is simply not to set  `--ema`.

**Comment by rwightman** [comment]
Fixed that, but a bunch more changes so let me know if anything else broke, it's possible to create a non `tf_` model for the efficientnets with PyTorch trained weights in timm now... seem ever so slightly faster and might have better end results due to better feature alignment, I haven't looked closely yet though

**Comment by andravin** [comment]
@rwightman everything is working for me so far, thanks. I actually stopped using `--ema` as you indicated it has doubtful benefit with the `cosine` learning rate schedule.

My only question now: it appears that `drop_rate` has no effect with feature detectors, because dropout is only applied before the classifier. Dropout appears not to be used in EfficientNetFeatures.

**Comment by rwightman** [comment]
@andravin indeed, the drop_rate in config has no impact, I was cutting and pasting those backbone kwargs in some zombie like state between baby naps...  I'll remove them to avoid confusion. I was thinking of giving DropBlock a try someday....

My D1 session after the init fix is looking really good, much better convergence in the first 50 epochs (.308) of training, interesting to see where it ends up vs before with the zero init classifier and some weird reliance on sync-bn.

**Comment by andravin** [comment]
@rwightman my `tf_efficientnet_d0` (8 x v100 `-b 16 --sync-bn --lr 0.2 --warmup-lr 0.01` no ema) is 30.96 mAP after 224 epochs. Hope to see a strong finish.

Is `--sync-bn` still recommended? Would there be a minimum batch-size for turning it off? (32?)
