### ISSUE TITLE
Question for next time - Detectron2

### ISSUE THREAD

**Issue by wenjun90** [rwightman/efficientdet-pytorch#20]
Hi @rwightman ,

Thank you for your great job.

Have you a plan for integration into detectron2?
The question is how do you think the performance is still keep like that if you intergrate to detectron2.

Thank you so much.

**Comment by rwightman** [comment]
@wenjun90 I thought it'd be fairly easy to combine, but looking closer it seems like it'd be some work to adapt things, the organization of detectron2 is a fair bit different, some adaptation would be needed for yxyx to xyxy, and the resulting models would be not be compatible weight wise and likely need some differences in code, etc. At this point I'd say the plan to integrate the two is low on my priority list, I'd want to experiment with different backbones and bifpn variations, semantic segmentation, and better augmentations using the current minimal framework first.

**Comment by rwightman** [comment]
I'll close this and leave #1 open
