### ISSUE TITLE
numpy  incompatibility  occured

### ISSUE THREAD

**Issue by lyw615** [rwightman/efficientdet-pytorch#205]
The conda environment   created  following requirements-sotabench.txt  by pip.   There is no error reported in the process, but 
 raised  in  train.py running  with messages  
`import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

Version 1.17.1  and 1.16. 0 of numpy   are tried with no improvement. Is this caused by numpy version incompatibility?

**Comment by rwightman** [comment]
@lyw615 not a bug here, issue with your pycocotools, I suggest you google as it's a common issue that is not specific to this codebase.
