### ISSUE TITLE
[FEATURE] Please publish 0.2.3

### ISSUE THREAD

**Issue by malcolmgreaves** [rwightman/efficientdet-pytorch#213]
**Is your feature request related to a problem? Please describe.**
The latest PyPI release is from 2020: https://pypi.org/project/effdet/#history

**Describe the solution you'd like**
A release of the most up-to-date code (version 0.2.3).

**Describe alternatives you've considered**
I can workaround by `pip install git+...`. But a PyPI package is nice :)

**Additional context**
Thank you for making this project!

**Comment by rwightman** [comment]
@malcolmgreaves I guess there are a few worthwhile changes on master. I was hoping to have time to port the advprop effdets first, but maybe I'll push a quick update in the next few days first...

**Comment by rwightman** [comment]
@malcolmgreaves fixed, advprop weights included

**Comment by malcolmgreaves** [comment]
Wonderful! Thank you very much
