### ISSUE TITLE
[BUG] train2017 is not found in config

### ISSUE THREAD

**Issue by AnhMinhTran** [rwightman/efficientdet-pytorch#217]
**Describe the bug**
`Train2017 is not found in config` using COCO dataset when loading `dataset_train, dataset_eval `for training

**To Reproduce**
1. Download COCO dataset
2. Extract val, train, and annotation folder

**Expected behavior**
Script start training COCO dataset

**Screenshots**

File structure
![Screenshot from 2021-04-30 17-06-13](https://user-images.githubusercontent.com/29029296/116660477-6d7df980-a9d6-11eb-9fbd-15ac3c5cd3ec.png)

Error
![Screenshot from 2021-04-30 17-05-54](https://user-images.githubusercontent.com/29029296/116660483-71118080-a9d6-11eb-90b5-031547ba3eaf.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - This repository version: Download  from GIT
 - PyTorch version w/ CUDA/cuDNN: 1.7.1

**Additional context**
Thank you so much for looking at the problem

**Comment by rwightman** [comment]
The folders are named as you have them, but the split in the code is called `train` not `train2017` as per 
* https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/data/dataset_config.py#L21 ... 
* https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/data/dataset_factory.py#L15

... so I'm not sure how/why it's looking for a split called `train2017` , did you modify code or pass diff split args? the 2017 is passed via the dataset arg, the split names are consistent across dataset types

**Comment by AnhMinhTran** [comment]
I found the issue, it was one of my args pass, somehow it found it way to the cofig. Closing the issue now
