### ISSUE TITLE
Tensor size mismatch, from data loader

### ISSUE THREAD

**Issue by Cli98** [rwightman/efficientdet-pytorch#23]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/19630616/83320342-873a1e00-a214-11ea-8de4-ef62d2a2ed36.png">

@rwightman Any reasons? And did you consider the case where image sizes are different?

**Comment by rwightman** [comment]
Looks like you're using dataset with more instances per image than coco? Look at the collate fn in loader, as per comment, not very robust. Increase max detections above the dataset max or cut the dimension of the value coming from the dataset during assignment ( not currently checked)

**Comment by Cli98** [comment]
> Looks like you're using dataset with more instances per image than coco? Look at the collate fn in loader, as per comment, not very robust. Increase max detections above the dataset max or cut the dimension of the value coming from the dataset during assignment ( not currently checked)

@rwightman I'm actually only interested in detection, not seg. Yes this is a customer dataset. BTW what's the purpose for fast_collate?

**Comment by rwightman** [comment]
It combines the elements coming from the dataset into batch size tensors of consistent dimension. This fast one tries to be minimal and do copies into prealloc tensors, keeps images in uint8 until later in loader/augmentation pipeline.

You could use pytorch default collate if you pad out any not batch dimensions to consistent values in your dataset yourself

**Comment by rwightman** [comment]
You could also limit the number of bbox, labels etc coming from your dataset per image to max_detections

**Comment by Cli98** [comment]
> You could also limit the number of bbox, labels etc coming from your dataset per image to max_detections in loader, which is currently 100

So are you suggesting that you fix bboxs collected with an upper bound?

**Comment by rwightman** [comment]
Yes, or increase the upper bound by changing that constant. All tensors
need to have equal dim though, so keep in mind every tensors passed to your
model with be padded out to max. So if only a few images have over 100
bbox, may be better to limit those ones...

**Comment by Cli98** [comment]
> Yes, or increase the upper bound by changing that constant. All tensors need to have equal dim though, so keep in mind every tensors passed to your model with be padded out to max. So if only a few images have over 100 bbox, may be better to limit those ones...
> […](#)

Alright I see. And where does the number 100 come from? As far as I consider, it is not even possible for coco dataset to have exactly same bbox per image. So 100 is the max possible bboxs per image for coco right?

**Comment by rwightman** [comment]
Yup, 100 is actually coming from the coco dataset itself so you'll find it in most coco based obj detection codes...

example from detectron2 config:
```
# Maximum number of detections to return per image during inference (100 is
# based on the limit established for the COCO dataset).
_C.TEST.DETECTIONS_PER_IMAGE = 100
```

**Comment by Cli98** [comment]
I have never aware of that. Can you tell me how to change this limit in your code? Or should I hand coding it in your fast collate function?

**Comment by rwightman** [comment]
umm, if you are looking at fast_collate you are are looking right at it...

https://github.com/rwightman/efficientdet-pytorch/blob/master/data/loader.py#L10

**Comment by Cli98** [comment]
> umm, if you are looking at fast_collate you are are looking right at it...
> 
> https://github.com/rwightman/efficientdet-pytorch/blob/master/data/loader.py#L10

Lol that's cool. Just too many lines to check. I willl change this parameter to see if it can work, maybe raise to 500...

**Comment by rwightman** [comment]
yes, padded with zeros, don't make it much larger than you need, it uses memory

**Comment by Cli98** [comment]
> yes, padded with zeros, don't make it much larger than you need, it uses memory

It works. Thank you.
