### ISSUE TITLE
format of target['bbox']

### ISSUE THREAD

**Issue by pluszeroplus** [rwightman/efficientdet-pytorch#24]
HI. I read Alex code on kaggle and I want to reproduce his work. I noticed that something changed after he share the code. Could you tell me what is the format of target['bbox'] in DetBenchTrain? I tried [x_min,y_min,x_max,y_max] first but i got something definitely not i expected. Then I noticed Alex used [x_min,y_min,width,height] but when i put this into the model i got a very large loss in the cls loss and nan in the box loss.

**Comment by rwightman** [comment]
Targets are expected to be yxyx right now as that's the Google model requirement, output from the brench is coco compatible xywh

**Comment by pluszeroplus** [comment]
Thank you very much
