### ISSUE TITLE
Example of finetuning on custom dataset (provided)

### ISSUE THREAD

**Issue by Chris-hughes10** [rwightman/efficientdet-pytorch#242]
Hi,

Great work on this Repo! In your README you mentioned that you were looking for clear examples of finetuning efficientdet on new datasets. I recently published a blog post on this using this repo with a timm backbone here: https://medium.com/data-science-at-microsoft/training-efficientdet-on-custom-data-with-pytorch-lightning-using-an-efficientnetv2-backbone-1cdf3bd7921f

Perhaps this could be helpful for people looking to get started.

Thanks

**Comment by rwightman** [comment]
@Chris-hughes10 awesome and a very useful reference, I'll add a link to the README shortly

**Comment by rwightman** [comment]
@Chris-hughes10 added to README, thanks
