### ISSUE TITLE
[BUG] Significant difference between Windows and Ubuntu validate.py result

### ISSUE THREAD

**Issue by AnhMinhTran** [rwightman/efficientdet-pytorch#251]
**Describe the bug**
The result in Windows is significantly worse than compared to when running the same script and dataset on Ubuntu

**To Reproduce**
1. Train a model
2. Validate on the same dataset but one on Windows and one on Ubuntu

**Expected behavior**
Same result from COCO evaluation

**Screenshots**
Ubuntu:
![image](https://user-images.githubusercontent.com/29029296/135033539-fab33926-6538-4946-a8de-72b23dac98e5.png)

Windows:
![image](https://user-images.githubusercontent.com/29029296/135033581-04736e12-c75c-4311-8b41-ef70ad6b5e8c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubuntu 18.04
 - PyTorch version w/ CUDA/cuDNN  : 1.9.0

**Additional context**

**Comment by ThiruRJST** [comment]
I would like to suggest a thing to check, In windows the file formats differ from ubuntu. So, is correct files are being used for validation. 
A similar issue was raised in pytorch forum, refer https://discuss.pytorch.org/t/what-can-cause-differences-in-training-a-model-in-windows-vs-ubuntu/48180

**Comment by rwightman** [comment]
@AnhMinhTran I have tested with windows in the past and i worked well, but there are often issues. For windows you have to make sure your coco package is a working version for one. I don't currently have a working windows setup to test so unfortunately up to you to figure out.

**Comment by rwightman** [comment]
@AnhMinhTran I had a chance to run on windows after my latest updates. No issues which matches previous tests.

Windows 10 w/ conda installed PyTorch 1.10 (cuDNN 11.3) matched validation exactly for mscoco on several pretrained models.

I can't support any exotic environments, custom datasets, etc... so will close now.
* install PyTorch in a conda environment exactly as per official instructions 
* `pip install -r requirements.txt` in that environment to get the correct pycocotools, timm, and omegaconf
* run `validate.py` from a command prompt with that anaconda env active
