### ISSUE TITLE
[BUG] pip can't find the package on Kaggle & Colab

### ISSUE THREAD

**Issue by lukeleeai** [rwightman/efficientdet-pytorch#265]
Hello, as who's suffering from "cuda out of memory" errors on Kaggle notebook, I can't wait to use your package. However, I run into errors when I try to install koila on both Kaggle and Colab notebooks. 

**Describe the bug**
`!pip install koila` outputs the following error message: `ERROR: Could not find a version that satisfies the requirement koila (from versions: none)
ERROR: No matching distribution found for koila` on Kaggle and Colab notebooks.

**To Reproduce**
1. Run `!pip install koila` on Kaggle / Colab

I'd appreciate it if anyone provides me with an alternate solution until this error gets fixed.

**Comment by rwightman** [comment]
@lukeleeai I have no idea what koila is, this is effdet

**Comment by lukeleeai** [comment]
You're right 😅 I'm sorry for the inconvenience. I accidentally posted the issue for another repository here. I appreciate your work.
