### ISSUE TITLE
[BUG] Stack shapes mismatch with non-square images

### ISSUE THREAD

**Issue by NicolasMICAUX** [rwightman/efficientdet-pytorch#296]
**Describe the bug**
I use a training script close to the one described [here](https://gist.github.com/Chris-hughes10/73628b1d8d6fc7d359b3dcbbbb8869d7).
I use non-squared images (1024, 512) from Kitti dataset.
getting error
`RuntimeError: stack expects each tensor to be equal size, but got [4, 64, 8, 16] at entry 0 and [4, 64, 16, 8] at entry 1` at line ~310 in `/usr/local/lib/python3.8/dist-packages/effdet/efficientdet.py`.

**To Reproduce**
Here is a minimal code example that shows the problem:
[reproduce_error.txt](https://github.com/rwightman/efficientdet-pytorch/files/12000069/reproduce_error.txt) (ipynb file renamed to txt for github upload compat)

**The problem**
I had a hard time fixing this. More than 2 weeks of struggle...
The problem is because the OmegaConf config that you're using is sorting lists. I use images with height < width, but the OmegaConf `config["image_size"]` keeps being sorted, so all the computations afterwards are false.

**Solution:**
You first have to modify line 13 in `efficientdet-pytorch/effdet/config/model_config.py`:  
`h = OmegaConf.create(flags={"allow_objects": True})`  
this keeps orders of tuples
I still have problems with some image sizes

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - installed with `pip install git+https://github.com/rwightman/efficientdet-pytorch`, so using v 0.4.1
Pytorch 2.0.1+cu117
Cuda compilation tools, release 11.3, V11.3.109 ; Build cuda_11.3.r11.3/compiler.29920130_0
timm==0.9.2
torchvision==0.15.2
pyyaml==6.0
numpy==1.23.5
pycocotools==2.0.6
omegaconf==2.3.0

**Comment by NicolasMICAUX** [comment]
(some suggested to set `_USE_SCALE=True` in /usr/local/lib/python3.8/dist-packages/effdet/efficientdet.py. I tried this but got other errors.

**Comment by NicolasMICAUX** [comment]
For example, I've got ~50% AP on Kitti with squared images (384x384), but max 25-30% AP with non-squared (1284x384 or 650x192)

**Comment by NicolasMICAUX** [comment]
I suspect the problem is in the transition between the efficientnet backbone and the detector.
I will re-open a PR if I figure out the problem.

**Comment by rwightman** [comment]
I've never observed any sorting behaviour with omegaconf as stated, and non-square images appear to work just fine... perhaps the rest of the train script/data pipe isn't feeding images of the shape matching the specified non-square image size?

```
    config = get_efficientdet_config(model_name)
    config['image_size'] = (640, 512)

    return create_model_from_config(
        config, bench_task=bench_task, num_classes=num_classes, pretrained=pretrained,
        checkpoint_path=checkpoint_path, checkpoint_ema=checkpoint_ema, **kwargs)
```

**Comment by SarBH** [comment]
@rwightman @NicolasMICAUX the order is guaranteed if you prefix your items with a `-` character. 
But if you dont, the elements you list are casted as a single space separated string.

I use Hydra and Omegaconf and ive seen the following behavior:

When my YAML config says:
```
image_size:
   512
   256
   ```

the value for image_size in the python interpreter is the string `"256 512"` (notice the swapping of the elements)

So naturally i would want to use the `-`:
```
image_size:
   - 512
   - 256
   ```
which gets read correctly as a list and maintains order. 

In my case these are parameters to instantiate a LightningModule (from pytorch lightning) and i get errors on the ternsorboard logger when logging a list, which is why i had initially removed the `-`. In any case, it is only a bug if you dont use the `-` to force the parametrs into an ordered list.

**Comment by rwightman** [comment]
@NicolasMICAUX oh, k. That's yaml syntax, unrelated to omegaconf or this repo .... - form is a valid list, so ordered, not even sure what the former one is don't think it's valid YAML, but it's not a list, probably just a key: value with the value being a string? So I think this behaviour is expected.
