### ISSUE TITLE
GPU memory issue

### ISSUE THREAD

**Issue by HansolEom** [rwightman/efficientdet-pytorch#38]
Thank you for your hard work.
I have a question. When I was trying to learn D5, I saw a change in memory.
This saw me using 31g of memory per gpu(v100-DGXs station) when loading the image, and after starting training I noticed that it dropped to 27g.
I couldn't see in the code why gpu memory goes up while loading the data. Can you tell me where this is happening?

**Comment by HansolEom** [comment]
Is it because you use the ema model?

**Comment by bonlime** [comment]
It could be due to `cudnn.benchmark = True` flag

**Comment by rwightman** [comment]
@HansolEom as @bonlime mentioned it could be benchmark hunting for the optimal algorithm for each layer, diff algos have different workspace sizes. There can also be some fluctuations on the transition between train eval and back.
