### ISSUE TITLE
# TypeError: forward() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by linhduongtuan** [rwightman/efficientdet-pytorch#42]
Hi Ross,
As you suggest, I have try to rerun the code from Alex here https://www.kaggle.com/shonenkov/training-efficientdet.
The notebook runs well using kaggle instance, but it gets error message: "TypeError: forward() takes 3 positional arguments but 4 were given", while I am trying to run on my local machine. My packages are effdet version 0.18.2, Pytorch version 1.5, and timm version 0.1.30.
I have also refer the code to wrap like this

class ExtendDetBenchTrain(DetBenchTrain):
    def __init__(self, model, config):
        super(ExtendDetBenchTrain, self).__init__(model, config)

    def forward(self, x, target):
        class_out, box_out = self.model(x)
        cls_targets, box_targets, num_positives = self.anchor_labeler.batch_label_anchors(
        x.shape[0], target['bbox'], target['cls'])
        loss, class_loss, box_loss = self.loss_fn(class_out, box_out, cls_targets, box_targets,      num_positives)
        output = dict(loss=loss, class_loss=class_loss, box_loss=box_loss)
        return output
but it still gets the same error
Can you give me an advice.
Many thank
Linh

**Comment by rwightman** [comment]
The code here has changed from when the notebook was written so very minor adjustments are needed. Two of the target box/cls args need to be combined in a dict. Should be staightforward if looking at both versions.

**Comment by linhduongtuan** [comment]
Thank Ross

**Comment by r-matsuzaka** [comment]
@rwightman 
Hi. Nice to meet you.
I have got the same error as mentioned in this issue 

So, I change the forward function like this by following
> Two of the target box/cls args need to be combined in a dict.

But I stil got the same error.
Could you tell me what might be wrong?    

> def forward(self, x):
>         x = self.backbone(x)
>         x = self.fpn(x)
>         x_class = self.class_net(x)
>         x_box = self.box_net(x)
>         return {x_class: x_box}

**Comment by r-matsuzaka** [comment]
@rwightman 
The code here has changed from when the notebook was written so very minor adjustments are needed. Two of the target box/cls args need to be combined in a dict. Should be staightforward if looking at both versions.

Hi.
I have got the same error. End I tried but stil suffer it.
Could you tell me the part of code to be fixed?

Regards,
Ryo

**Comment by r-matsuzaka** [comment]
Sorry I thought I found the part!
Thank you.

**Comment by r-matsuzaka** [comment]
Sorry, after I used the old version, I could run the training.
