### ISSUE TITLE
How set img_size at DetBenchPredict class?

### ISSUE THREAD

**Issue by linhduongtuan** [rwightman/efficientdet-pytorch#43]
I Ross,
I am still following the code of Alex Schonenkov, here https://www.kaggle.com/shonenkov/inference-efficientdet/comments?scriptVersionId=34956042
And this time I get an error at DetBenchPredict class. I know Alex used your code at training branch (he used DetBenchEval) and I am using your current master branch. My weights come from training process using master branch.
So it lacks of img_size at forward function of DetBenchPredict.
Do you have any suggestion to fix the problem?
Linh

**Comment by rwightman** [comment]
@linhduongtuan fill it with the size of the original image if you're setting img_scale to something != otherwise just set to the size of the image you're sending to the model if img_scale==1, it's used for clipping the bbox to image bounds and wasn't done originally (but was a mistake not to)
