### ISSUE TITLE
Bug in model_config - tf_efficientdet_d7

### ISSUE THREAD

**Issue by ngokhoa96** [rwightman/efficientdet-pytorch#47]
Hi @rwightman,

Thank you for your amazing work.

When I tried using tf_efficientdet_d7, I found out it actually used tf_efficientdet_d6 backbone. Diving a little into your code, I found a small bug in efficientdet_model_param_dict in model_config.py.

```
    tf_efficientdet_d7=dict(
        name='tf_efficientdet_d7',
        backbone_name='tf_efficientnet_b6', # ~~> should be b7
        image_size=1536,
        fpn_channels=384,
        fpn_cell_repeats=8,
        box_class_repeats=5,
        anchor_scale=5.0,
        fpn_name='bifpn_sum',  # Use unweighted sum for training stability.
        backbone_args=dict(drop_rate=0.5, drop_path_rate=0.2),
        url='https://github.com/rwightman/efficientdet-pytorch/releases/download/v0.1/tf_efficientdet_d7-f05bf714.pth'
    ),
```

Hope you fix it soon. 

Have a nice day.

**Comment by rwightman** [comment]
It's not a bug, D7 uses B6 backbone as per the official impl. The weights wouldn't work if that wasn't the case. You can make your own config and train from scratch if you want to try it.

**Comment by jinfagang** [comment]
@rwightman  Do u have a speed benchmark on GTX 1080ti on all variants of efficientdets.
