### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by Naivepro1990** [rwightman/efficientdet-pytorch#49]
Hi,

I know that you have given a link to finetuning on custom dataset. But being a naive programmer, is there a way to use your training script for finetuning. For example load your train model and fine tune it with a custom dataset which has same images and annotations as mscoco.

**Comment by rwightman** [comment]
You can use the training script here for custom datasets so long as you have your custom dataset in a coco compatible annotation format (train / val json files).

To finetune, during model creation, adding a one liner that relplaces the HeadNet would be the easiest solution. 
```
model.class_net = HeadNet(config, num_outputs=your_num_classes, norm_kwargs=dict(eps=.001, momentum=.01))
```
You could probably get a bit more granular and just replace the final layer of the head net
`model.class_net.predict = ...` but that requires some more code.

In both cases you need to hack together a weight init that only inits the modified head weights properly, especially the predict weights. It's best to do this by modifying the create factory, or creating your own... at line 28 after pretrained weights are loaded, not where the FIXME is.

https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/factory.py#L28

**Comment by rwightman** [comment]
Also, default training hparams won't necessarily work great for finetuning. I'd start with `--opt adam --sched plateau` and lr between 1e-3 to 1e-4.

**Comment by Naivepro1990** [comment]
Thanks,

It will be good idea to include the finetuning as an option in the code, by default it should be false.

And instead of hardcoding the prediction classes should be a parameter

**Comment by rwightman** [comment]
Yup, it's definitely on the todo list, likely next thing to add here with
result of my resnet backbone experiements, but have a number of other
project threads to wrap up first :)

**Comment by Naivepro1990** [comment]
@rwightman It seems the above solution doesn;t quite work for finetuning as the location you specified HeadNet is not  defined. I did tried to import but still it gives error.
