### ISSUE TITLE
Can I fork your repo and change the liscence with MIT license

### ISSUE THREAD

**Issue by WangLibo1995** [rwightman/efficientdet-pytorch#51]
Due to kaggle GWD  need to use MIT liscense :(

**Comment by rwightman** [comment]
@WangLibo1995 that's not how licensing works, and you should not and do not need to do that... there are already threads for the kaggle challenge you are refering to that state as much,  I actually commented on Apache/BSD question in a thread so read that. 

You can mix permissive licenses but you need to retain the license/copyrights of the original and for Apache include attribution (note that your solution uses code from here) and then you can license your own code with MIT.

**Comment by WangLibo1995** [comment]
> @WangLibo1995 that's not how licensing works, and you should not and do not need to do that... there are already threads for the kaggle challenge you are refering to that state as much, I actually commented on Apache/BSD question in a thread so read that.
> 
> You can mix permissive licenses but you need to retain the license/copyrights of the original and for Apache include attribution (note that your solution uses code from here) and then you can license your own code with MIT.

Thank you for your explanation. Now I am clear, and I am really your fans. :)
