### ISSUE TITLE
Validation outputs all zeros on ms coco

### ISSUE THREAD

**Issue by Naivepro1990** [rwightman/efficientdet-pytorch#54]
Hi,

Using the default validation parameters given on the github gives all zeros on mscoco as shown below. Is it possible to know what can be the problem. 

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50         | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75         | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95  | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95  | area=   all | maxDets= 10 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95  | area=   all | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95  | area= small | maxDets=100 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95  | area=medium | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95  | area= large | maxDets=100 ] = 0.001

**Comment by rwightman** [comment]
No idea but you didn't provide any info, I assume you may have chosen a model without the tf_ prefix that has no weights.
