### ISSUE TITLE
Finetuning Training d7

### ISSUE THREAD

**Issue by Naivepro1990** [rwightman/efficientdet-pytorch#55]
Hi rwightman,

It doesn't matter what batchsize I use for d7, it doesn't fit in the GPU (16GB). I am finetuning and following is the runtime command.

./distributed_train.sh 2 /datasetlocation --model tf_efficientdet_d7 -b 1 --amp --lr .04 --sync-bn --opt adam --fill-color mean --sched plateau

Please can you let me know about your setting for training d7 or am I doing something wroing.

**Comment by rwightman** [comment]
In my opinion there is no point in trying to train the D6 or D7 models without significant hardware resources (ie 8x 32GB V100s). I am not surprised it doesn't fit, I've never bothered to try it training times and batch sizes are already questionable for a modest system.
