### ISSUE TITLE
How to feed tensor to target["img_size"] & target["img_scale"] for DetBenchTrain()?

### ISSUE THREAD

**Issue by zlyin** [rwightman/efficientdet-pytorch#56]
Hello Ross, 
  Thank you for this awesome project! 
  I'm been playing with it to build a pipeline and got stuck by the annoying input of `target["img_scale"] & target["img_size"]` required by the `DetBenchTrain` class. I expect the model to output `pred boxes` during validation, but I can't feed the right target to the model.

```
def forward(self, x, target):
        class_out, box_out = self.model(x)
        cls_targets, box_targets, num_positives = self.anchor_labeler.batch_label_anchors(
            x.shape[0], target['bbox'], target['cls'])
        loss, class_loss, box_loss = self.loss_fn(class_out, box_out, cls_targets, box_targets, num_positives)
        output = dict(loss=loss, class_loss=class_loss, box_loss=box_loss)
        if not self.training:
            # if eval mode, output detections for evaluation
            class_out, box_out, indices, classes = _post_process(self.config, class_out, box_out)
            output['detections'] = _batch_detection(
                x.shape[0], class_out, box_out, self.anchors.boxes, indices, classes,
                target['img_scale'], target['img_size'])
        return output
```

For example, my `batch_size=2, image_size=512`, how should I feed in these 2 tensors? The bug pops whatever I'm trying to feed. Please help.

Great thanks!

**Comment by lgvaz** [comment]
I believe you only need to feed those during validation, I use the following:
```python
targets["img_scale"] = tensor([1.0] * batch_size, dtype=torch.float)
targets["img_size"] = tensor([images[0].shape[-2:]] * batch_size, dtype=torch.float)
```

But you can only do that in some specific circumstances that Ross addressed [here](https://github.com/rwightman/efficientdet-pytorch/issues/50#issuecomment-654509922)

**Comment by zlyin** [comment]
Hi @lgvaz, thank you for your feedback, let me do it and have a try! Thank you!
