### ISSUE TITLE
What is the difference between timm and gen-efficientnet?

### ISSUE THREAD

**Issue by HansolEom** [rwightman/efficientdet-pytorch#6]
I confirmed that there is an efficientnet in the gen-efficientnet you made and an efficientnet in the timm.
Does it matter whether you use timm's efficientnet or gen-efficientnet's efficientnet?

**Comment by rwightman** [comment]
They are the same at the core, weights exactly the same. Timm version has a few extras and more dependencies, but I may stick with it since it has training helpers that I will use for the train code

**Comment by HansolEom** [comment]
> They are the same at the core, weights exactly the same. Timm version has a few extras and more dependencies, but I may stick with it since it has training helpers that I will use for the train code

thanks for your reply!
