### ISSUE TITLE
batched nms not working properly?

### ISSUE THREAD

**Issue by hamadichihaoui** [rwightman/efficientdet-pytorch#64]
<img width="304" alt="nms_issue" src="https://user-images.githubusercontent.com/13422842/88475902-c34fdd80-cf3c-11ea-9c29-89093585adbf.PNG">
above is the output of the model predicting only 1 class. Given that NMS with iou_threshold=0.5 is applied when outputing the detected bboxes. 

`top_detection_idx = batched_nms(boxes, scores, classes, iou_threshold=0.5)`

it looks like the nms was not applied unless I am missing something?

**Comment by rwightman** [comment]
haven't seen any other issues about this so chances are there is something off in your setup? could always try reverting to the old NMS that was in here in early commits, or pulling a soft-nms from somewhere else

**Comment by samshipengs** [comment]
@hamadichihaoui did you figure out why? I'm observing similar things, and seems like latest version is giving different/lower result than the version that kaggle kernel used (im closely following the kernels setup)

**Comment by Naivepro1990** [comment]
Hi @hamadichihaoui ,

Have you written the code to output the images with labels and can you share the code for outputing the images?
