### ISSUE TITLE
How to find the include object accord var box_targets_at_level in loss.py

### ISSUE THREAD

**Issue by cswwp** [rwightman/efficientdet-pytorch#67]
Hi @rwightman, thanks for sharing beautiful code. How to find the include object accord var box_targets_at_level in loss.py, such as box_targets_at_level[0] shape is [batchsize, 36864, 4], how can i confirm which box  include object in  36864 boxes, just judge box_targets_at_level[0] > 0? looking forward your reply

**Comment by rwightman** [comment]
In the loss fn, it should be possible to use the already computed `cls_targets_non_neg` as a mask to select boxes that have a valid target class for the same level

**Comment by cswwp** [comment]
> In the loss fn, it should be possible to use the already computed `cls_targets_non_neg` as a mask to select boxes that have a valid target class for the same level

Does it mean if box_targets_at_level[0][0][:] = [0.0, 0.0, 0.0, 0.0], then box_targets_at_level[0][0] is a invalid box which not include an object? @rwightman
