### ISSUE TITLE
ImportError: cannot import name 'get_act_layer'

### ISSUE THREAD

**Issue by linkchainiii** [rwightman/efficientdet-pytorch#74]
File "D:\python\flyai_python\TBDetection_FlyAI_effientdet1\effdet\efficientdet.py", line 16, in <module>
    from timm.models.layers import create_conv2d, drop_path, create_pool2d, Swish, get_act_layer
ImportError: cannot import name 'get_act_layer'

**Comment by rwightman** [comment]
update your version of timm
