### ISSUE TITLE
Setting IOU threshold

### ISSUE THREAD

**Issue by ylmzkaan** [rwightman/efficientdet-pytorch#79]
Hi,

I want to set the IOU threshold for bounding box matching to a custom value but I am not sure where exactly I should do that. Just to be sure, is it the input arg match_threshold of the AnchorLabeler class that I should adjust?

**Comment by rwightman** [comment]
IOU threshold is changeable here: https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/anchors.py#L217-L222

TODO is to add it to config/arguments but it doesn't seem necessary to change to often so hasn't been a high priority.

**Comment by stralen999** [comment]
exactly how? by addig self.iou_threshold = 0.2 ?
