### ISSUE TITLE
About run time

### ISSUE THREAD

**Issue by youngwanLEE** [rwightman/efficientdet-pytorch#8]
Hi, 

I'm very impressed by your wonderful work.

I wonder your implementation models are as fast as original work.

I can't find the inference time of your implementation models.

Could you let us know the inference time, too?

I have tried to add the biFPN into [CenterMask](https://github.com/youngwanLEE/centermask2) and experienced that biFPN was slower than the original FPN because of its many layers.

**Comment by rwightman** [comment]
I've only posted benchmark numbers for image throughput running validation on mscoco, which includes the data preprocessing time. All in all quite good with AMP enabled and good batch size. Faster than original when I last checked.

I have not run any specific inference benchmarks. You'd likely want to do that yourself on the specific hardwre you're targetting. On a GPU, the default bifpn would be slower than you'd expect for the parameter count, it's using depthwise separable convs which do not make for the most optimal utilization of GPU resources. The swish activations are fairly expensive as well. For a latency sensitive network, you'd likely want to use the ConvBnAct  (set `separable_conv=False`), set the activation fn to ReLU or ReLU6, increasing the FPN channel count a bit could compensate for some of the accuracy the above changes might add without adding too much latency back.

**Comment by youngwanLEE** [comment]
@rwightman 

Thanks for reply :)

**Comment by jinfagang** [comment]
@youngwanLEE How's the peformance gain with Bi-FPN in centermask?
