### ISSUE TITLE
Pypi release

### ISSUE THREAD

**Issue by lgvaz** [rwightman/efficientdet-pytorch#80]
Hi Ross,

We currently cannot publish our package ([icevision](https://github.com/airctic/icevision)) to pypi with your repo as a dependency because pypi doesn't allow external dependencies (e.g. Github dependencies).

If manually releasing is too much trouble, we will be happy to contribute with a workflow file that automatically publishes your package to pypi. The provided workflow is also very easy transferable to your other repos.

Thanks :tada:

**Comment by rwightman** [comment]
@lgvaz  I've been 'close' to finishing some work on another branch and merging for some time now.. but I keep adding /tweaking things. I was waiting to actually get that in but it's been awhile.

Just publishing the current master for pypi is fine? I can do that today.

**Comment by lgvaz** [comment]
It would help immensely Ross :heart:

**Comment by rwightman** [comment]
@lgvaz done, please reopen if something didn't work out.

**Comment by lgvaz** [comment]
Hey @rwightman me again :sweat_smile:, are we ready for another release?
