### ISSUE TITLE
Use NHWC dataformat

### ISSUE THREAD

**Issue by subhankar-ghosh** [rwightman/efficientdet-pytorch#83]
Hey Ross @rwightman ,

Is there an easy way to use NHWC while training or does it include code changes? Because NHWC is known to give higher performance.

Thanks

**Comment by rwightman** [comment]
@subhankar-ghosh it does require code changes, I recently implemented it for my classification backbones at https://github.com/rwightman/pytorch-image-models .. the changes there were minimal (might run into more issues here), but it's not quite ready to use based on my tests. 

Performance was increased for a number of models, but one had to use the latest NGC Pytorch containers with CUDA11 and cuDNN 8 to see any gains, and then there were mulitple regressions for various models, issues with AdaptiveAveragePool numeric accuracy and NaN... once all that was figured out for inference, I tried training and convergence wasn't matching normal layout.. I gave up at that point (for now). I'll look into it here in a few iterations of cuDNN and PyTorch point releases to see if bugs have been fixed.

**Comment by rwightman** [comment]
I've tried supporting this (just the basics without and major model changes) on this branch https://github.com/rwightman/efficientdet-pytorch/tree/more_datasets ... unlike my classification models, it ended up slower, I think it requires some extra tensor copies at some points that slow it down
