### ISSUE TITLE
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

### ISSUE THREAD

**Issue by innat** [rwightman/efficientdet-pytorch#88]
Hello @rwightman, Thanks for your great repo. 

However, I was trying to run this notebook which had used over [here ](https://www.kaggle.com/shonenkov/inference-efficientdet/notebook)by its previous version of this repo. In the inference time, it called the model like following:

```python
def make_predictions(images, score_threshold=0.22):
    images = torch.stack(images).cuda().float()
    predictions = []
    with torch.no_grad():
        det = net(images, torch.tensor([1]*images.shape[0]).float().cuda())
        for i in range(images.shape[0]):
            boxes = det[i].detach().cpu().numpy()[:,:4]    
            scores = det[i].detach().cpu().numpy()[:,4]
            indexes = np.where(scores > score_threshold)[0]
...
...
```

I've found that the `DetBenchEval` method has renamed with `DetBenchPredict`, and defined [here](https://github.com/rwightman/efficientdet-pytorch/blob/2fc4e0e107c969090380d0be1a7ad7552dc00c63/effdet/bench.py#L62). And now the forward function is taking additionally `img_size` argument (`forward(self, x, img_scales, img_size):`. And so, I've tried to change accordingly:

```python
    images = torch.stack(images).cuda().float()
    predictions = []
    with torch.no_grad():
        print(images.shape[0])
        
        det = net(images, 
                  torch.tensor([1]*images.shape[0]).float().cuda(),
                  torch.tensor([512]*images.shape[0])) # 512 for img_size 
        
        for i in range(images.shape[0]):
            boxes = det[i].detach().cpu().numpy()[:,:4]    
            scores = det[i].detach().cpu().numpy()[:,4]
            indexes = np.where(scores > score_threshold)[0]
...
...
```

And it gave me `RuntimeError` and points over [here](https://github.com/rwightman/efficientdet-pytorch/blob/2fc4e0e107c969090380d0be1a7ad7552dc00c63/effdet/anchors.py#L214)

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "c:\users\innat\anaconda3\envs\alaska\lib\site-packages\effdet\anchors.py", line 214, in _batch_detection
    boxes = decode_box_outputs(box_outputs.float(), anchor_boxes, output_xyxy=True)
    if img_scale is not None and img_size is not None:
        boxes = clip_boxes_xyxy(boxes, img_size / img_scale)  # clip before NMS better?
                ~~~~~~~~~~~~~~~ <--- HERE

    scores = cls_outputs.sigmoid().squeeze(1).float()
  File "c:\users\innat\anaconda3\envs\alaska\lib\site-packages\effdet\anchors.py", line 167, in clip_boxes_xyxy
def clip_boxes_xyxy(boxes: torch.Tensor, size: torch.Tensor):
    boxes = boxes.clamp(min=0)
    size = torch.cat([size, size], dim=0)
           ~~~~~~~~~ <--- HERE
    boxes = boxes.min(size)
    return boxes
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated
```

Any catch? Anyway, I'm sorry if it looks dumb question, not much familiar with the torch ecosystem. If the above information isn't enough, I can explain in many details.

**Comment by rwightman** [comment]
@innat those changes did make things a bit more complicated when you don't use/need them.. tried to make them optional but torchscript complained so had to keep them as mandatory for now, when you use them with variable sized images being predicted on the square canvas, it allows clipping of the detection results to clip boxes that are in the letter box region of the images. Doing that before nms seemed to improve speed slightly and more importantly the end mAP results.

The scales needs to be a [batch_size, 1] float tensor, of ones if you aren't trying to restore the scale of your bbox to a rescaled input, and the img_size needs to be a [batch_size, 2] tensor of form width, height for the size of the original image in original aspect ratio. Again, if you aren't caring about rescaling or clipping, you should set it to the img_size.

torch.ones((images.shape[0], 2)) * 512 should work for img_size ... and just torch.ones(images.shape[0]) for scale

**Comment by innat** [comment]
Oh, I see. Thanks. @rwightman
