### ISSUE TITLE
Number classes for COCO is 81, but it is 90 in the config?

### ISSUE THREAD

**Issue by chuong98** [rwightman/efficientdet-pytorch#9]
Hello. Thanks for your implementation.
I read through the config.py and see the number class =90, therefore the weight of `cls_net.predict.conv_pw` is [810x fpn_feature x1x1], where the number of anchor =9. (90x9=810)

This is different with I expect, since COCO has 80 foreground classes, it should be 80x9=720 instead.

**Comment by rwightman** [comment]
That's the way the Google researchers set up their model, I'd remap the classes down to 81 but they left the gaps. Since I ported their weights I left that. I'll likely add an 81 class mode for weights I train in the future
