### ISSUE TITLE
config files description

### ISSUE THREAD

**Issue by Suzan009** [rwightman/efficientdet-pytorch#90]
Some few things need to be ensured.
In config file:

`config.num_classes = instance_item` 

So, if I've 4 object/instance (cat, rat, bat, dog), in that case do I need to set the `.num_classes` to 5 (instance_item + background). 

## Secondly,
If I've a trained model, trained on 256 resized input image with its transformed bounding box, how would I handle bounding box adjustment when making inference on small or larger test image? 

## thirdly,
For `efficient-det` model here, what are the available classification model/backbone models with pre-trained weights? 

## and lastly,
it's not related to this repo (sorry to ask so, need some pointer). 
I'm training a object detection model with `efficient-det` model. I did dome bounding box augmentation (h/v-flip, random-resize-crop, cutout etc). In the training time, suddenly in the middle of epoch (let's say epoch 10), a following error occurred (it's not consistent in epoch 10, random phenomena): 

```
TypeError: expected Tensor as element 0 in argument 0, but got nd.array
```
Any catch? In the `traceback`, it points to the line where image transformation occurred in the data loader. So, my guess was, I am doing some stupid augmentation but those augmentation are used for object detection, simple ones.

**Comment by rwightman** [comment]
I'm working on a branch right now that has big improvements for fine-tuning (changing the num classes for the head on model creation) https://github.com/rwightman/efficientdet-pytorch/tree/more_datasets

Resolution resizing is handled in the example validation and train scripts, it's done in the same way as the original TF EfficientDet impl. Longest edge is resized to the anchor layout (model) image_size w/ aspect ratio maintained, it is positioned at 0,0 (upper left), and any letterboxing is in the bottom or right edge with the fill color. 

The original weights are trained with that approach, you can of course do the augmentation pipelie differently and others have.

I don't know about your error, if your mixing other transforms with my loader/dataset arrangement there may be something missed. My loader/collate fn expects either python scalars or numpy arrays from the augmentation transforms, the model only accepts torch tensors. So using any of my components, my datasets output np.arrays, the transforms go PIL image or np.array -> np.array, the collate fn np.array -> torch.tensor, model torch.tensor -> torch.tensor
