### ISSUE TITLE
How could the model be exported as a jit model?

### ISSUE THREAD

**Issue by thhart** [rwightman/efficientdet-pytorch#93]
I would like to use my custom trained model in torch jit. Is this possible with model?

**Comment by rwightman** [comment]
@thhart latest commit allows jit scripting of both the model and model wrapped in a bench (train or predict). However, it requires that the head is changed to a form that breaks weight compatibility.

If you have existing weights you want to use, or want to use pretrained weights usage would look like
```
bench = create_model(....)
stashed_config = model.confg # grab config if needed for your training/val script before JIT
load_checkpoint(model, ...) # must load checkpoint w/ old model format here (or pretrained via create_model)
bench.model.toggle_head_bn_level_first()  # switch BN ModuleList order in Head to be torcscript compatible
bench = torch.jit.script(bench)
```

after you've trained such a model, you can make a config in the model_config that always has `head_bn_level_first` set to True to load the weights (if you happened to train the model jit scripted). If you just want to use for inference it's easy, train normally, load weights, toggle head mode, script, save scripted model
