### ISSUE TITLE
EfficientDet-D0 weights in the repo for fine-tuning on the Custom dataset

### ISSUE THREAD

**Issue by Ekta246** [rwightman/efficientdet-pytorch#95]
When I download the tf_efficientdet-d0 model pretrained weights, it redirects to a repo which no more exists giving 404 error.
Any help with this?
However, the efficientdet_d0.pth is downloadable but the class_net.predict.conv_pw.weight layer has some abnormal bias tensor of [810, 64, 1, 1] which arises a problem while finetuning the pretrained weights on my custom dataset.

Any help appreciated! 
TIA

**Comment by innat** [comment]
I think you can have all weights from [here](https://www.kaggle.com/mathurinache/efficientdet) also.

**Comment by Ekta246** [comment]
> I think you can have all weights from [here](https://www.kaggle.com/mathurinache/efficientdet) also.

Thanks @innat 

Also, could you tell how can we modify the class_net layers in order to get rid of this error

"size mismatch for class_net.predict.conv_pw.weight: copying a param with shape torch.Size([810, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 64, 1, 1]).
        size mismatch for class_net.predict.conv_pw.bias: copying a param with shape torch.Size([810]) from checkpoint, the shape in current model is torch.Size([9])."

I am fine-tuning the EfficientDet on a Custom Dataset using 1 class and using the pretrained URL available.

**Comment by innat** [comment]
Check these out. [(1)](https://stackoverflow.com/questions/53612835/size-mismatch-for-fc-bias-and-fc-weight-in-pytorch), [(2)](https://discuss.pytorch.org/t/tensor-size-mismatch/31897) to get pointer.

**Comment by Ekta246** [comment]
First, thanks for the pointer and the help.
However, I know when I make the pointer there. Also, I have changed the
num_classes config while loading the pretrained Coco Checkpoint. I don't
where do I still need to modify.
But thanks a ton!

Thanks

**Comment by rwightman** [comment]
The weight links in the README have a mistake, I'm probably going to remove those altogether shortly, the links in the config file are correct https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/config/model_config.py and there is model zoo functionality that downloads them for you when you create a model via the factory method. 

To finetune with different # classes you need to replace the head. You must load pretrained weights before you do that or the size won't match, 810 (9x90) is a dimension from the coco head.

There are some features on the branch I'm working on that make it easier to fine-tune, you can pass num-classes in to the creation method and it'll replace the head for you, at the correct point in model init. https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/config/model_config.py

**Comment by Ekta246** [comment]
> replace the head

Thanks for the reply. I am actually changing the # of classes and see the head is 9 (9x1) dimension. So it gives a Tensor mismatch on loading the pre-trained weights.

**Comment by rwightman** [comment]
yeah, the pretrained weights need to be loaded first, before you modify the head, or you need to modify the state dict to exclude the old head tensors if. you want to do it after.

**Comment by Ekta246** [comment]
Thanks for the quick response @Ross. I guess I am doing the same thing as
also referencing Alex's work.

I could see the same tensor mismatch error

from effdet import get_efficientdet_config, EfficientDet, DetBenchTrain
from effdet.efficientdet import HeadNet
import torch

def get_net():
    config = get_efficientdet_config('tf_efficientdet_d0')
    net = EfficientDet(config, pretrained_backbone=False)
    checkpoint = torch.load(
'/home/ekta/AI_current/efficientdet-pytorch/tf_efficientdet_d0-d92fd44f.pth'
)
    net.load_state_dict(checkpoint)
    config.num_classes = 1
    config.image_size = 512
    net.class_net = HeadNet(config, num_outputs=config.num_classes,
norm_kwargs=dict(eps=.001, momentum=.01))
    return DetBenchTrain(net, config)

net = get_net()
